import { db } from "./firebase-config.js";
import { collection, doc, getDoc, getDocs, limit, orderBy, query, where } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const money=v=>new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0}).format(Number(v)||0);
const fmt=v=>{if(!v)return"Date to be announced";const d=v.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat("en-CA",{dateStyle:"long",timeStyle:"short"}).format(d)};
const defaults={settings:{groupName:"1st Sault Ste. Marie Scout Group",publicEmail:"",phone:"",meetingLocation:"Sault Ste. Marie, Ontario"},home:{heroTitle:"Adventure starts here.",heroSubtitle:"Helping young people build confidence, friendships and skills through meaningful adventures.",heroButton:"Explore our sections",aboutTitle:"Scouting in Sault Ste. Marie",aboutText:"The 1st Sault Ste. Marie Scout Group provides youth with opportunities to learn, lead, serve and explore in a welcoming environment."},apple:{title:"Apple Day",description:"Apple Day is a long-standing Scouting tradition that helps fund local programming, equipment and camps.",date:"To be announced",location:"Sault Ste. Marie",donationUrl:"",amountRaised:0,goal:5000}};
async function read(c,i,f){try{const s=await getDoc(doc(db,c,i));return s.exists()?{...f,...s.data()}:f}catch(e){console.warn(e);return f}}
async function core(){const[s,h,a]=await Promise.all([read("settings","general",defaults.settings),read("siteContent","homepage",defaults.home),read("siteContent","appleDay",defaults.apple)]);
$("brandName").textContent=s.groupName;$("footerName").textContent=s.groupName;$("heroTitle").textContent=h.heroTitle;$("heroSubtitle").textContent=h.heroSubtitle;$("heroButton").textContent=h.heroButton;$("aboutTitle").textContent=h.aboutTitle;$("aboutText").textContent=h.aboutText;
$("appleTitle").textContent=a.title;$("appleDescription").textContent=a.description;$("appleDate").textContent=a.date;$("appleLocation").textContent=a.location;$("raised").textContent=money(a.amountRaised);$("goal").textContent=money(a.goal);
const pct=Math.min(100,Math.round(((Number(a.amountRaised)||0)/Math.max(1,Number(a.goal)||1))*100));$("progressBar").style.width=pct+"%";$("progressTrack").setAttribute("aria-valuenow",pct);
if(/^https?:\/\//i.test(a.donationUrl||"")){for(const el of [$("appleDonate"),$("donateNav")]){el.href=a.donationUrl;el.target="_blank";el.rel="noopener"}}
$("contactEmail").textContent=s.publicEmail||"Not yet added";$("contactEmail").href=s.publicEmail?"mailto:"+s.publicEmail:"#";$("contactLocation").textContent=s.meetingLocation||"Sault Ste. Marie, Ontario";
if(s.phone){$("phoneRow").hidden=false;$("contactPhone").textContent=s.phone;$("contactPhone").href="tel:"+s.phone.replace(/[^\d+]/g,"")}}
async function sections(){const t=$("sectionsGrid");try{const snap=await getDocs(query(collection(db,"sections"),orderBy("order","asc")));const items=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false);t.innerHTML=items.length?items.map(x=>`<article class="section-card"><span class="age">${esc(x.ageRange||"")}</span><h3>${esc(x.displayName||x.name||x.id)}</h3><p>${esc(x.description||"")}</p></article>`).join(""):'<p class="empty">No sections have been published yet.</p>'}catch(e){console.error(e);t.innerHTML='<p class="empty">Sections could not be loaded. Check Firestore rules.</p>'}}
async function events(){const t=$("eventsGrid");try{const snap=await getDocs(query(collection(db,"events"),where("published","==",true),orderBy("start","asc"),limit(6)));const items=snap.docs.map(d=>d.data()).filter(x=>!x.start||x.start.toDate()>=new Date(Date.now()-86400000));t.innerHTML=items.length?items.map(x=>`<article class="event-card"><time>${esc(fmt(x.start))}</time><h3>${esc(x.title||"Upcoming event")}</h3><p>${esc(x.description||"")}</p><p class="location">${esc(x.location||"Location to be announced")}</p></article>`).join(""):'<p class="empty">No upcoming public events have been posted.</p>'}catch(e){console.error(e);t.innerHTML='<p class="empty">Events could not be loaded. Firebase may ask you to create a query index.</p>'}}
async function announcement(){try{const snap=await getDocs(query(collection(db,"announcements"),where("published","==",true),orderBy("createdAt","desc"),limit(1)));if(!snap.empty){const x=snap.docs[0].data();$("announcementTitle").textContent=x.title||"Announcement";$("announcementText").textContent=x.content||"";$("announcement").hidden=false}}catch(e){console.warn(e)}}
$("year").textContent=new Date().getFullYear();$("menuBtn").onclick=()=>{const open=$("nav").classList.toggle("open");$("menuBtn").setAttribute("aria-expanded",open)};$("nav").onclick=e=>{if(e.target.tagName==="A")$("nav").classList.remove("open")};
await Promise.all([core(),sections(),events(),announcement()]);
