import { auth, db } from "./firebase-config.js";
import { EmailAuthProvider,browserLocalPersistence,onAuthStateChanged,reauthenticateWithCredential,sendPasswordResetEmail,setPersistence,signInWithEmailAndPassword,signOut,updatePassword } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { addDoc,collection,deleteDoc,doc,getDoc,getDocs,orderBy,query,serverTimestamp,setDoc,Timestamp,updateDoc } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let editor=null;
const defaults={home:{heroTitle:"Adventure starts here.",heroSubtitle:"Helping young people build confidence, friendships and skills through meaningful adventures.",heroButton:"Explore our sections",aboutTitle:"Scouting in Sault Ste. Marie",aboutText:"The 1st Sault Ste. Marie Scout Group provides youth with opportunities to learn, lead, serve and explore in a welcoming environment."},apple:{title:"Apple Day",description:"Apple Day is a long-standing Scouting tradition that helps fund local programming, equipment and camps.",date:"To be announced",location:"Sault Ste. Marie",donationUrl:"",amountRaised:0,goal:5000},settings:{groupName:"1st Sault Ste. Marie Scout Group",publicEmail:"",phone:"",meetingLocation:"Sault Ste. Marie, Ontario",city:"Sault Ste. Marie",province:"Ontario"}};
await setPersistence(auth,browserLocalPersistence);
function msg(t,type="success"){const x=$("adminMessage");x.textContent=t;x.className="admin-message "+type;setTimeout(()=>{if(x.textContent===t){x.textContent="";x.className="admin-message"}},5000)}
function err(e){return({"auth/invalid-credential":"The email address or password is incorrect.","auth/too-many-requests":"Too many attempts. Try again later.","auth/network-request-failed":"A network error occurred."})[e?.code]||e?.message||"An unexpected error occurred."}
async function read(c,i,f){const s=await getDoc(doc(db,c,i));return s.exists()?{...f,...s.data()}:f}
async function log(action,target){try{await addDoc(collection(db,"activityLog"),{action,target,userUid:auth.currentUser.uid,userEmail:auth.currentUser.email,createdAt:serverTimestamp()})}catch(e){console.warn(e)}}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMessage").textContent="";try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch(x){$("loginMessage").textContent=err(x)}};
$("forgotBtn").onclick=async()=>{const email=$("loginEmail").value.trim();if(!email){$("loginMessage").textContent="Enter your email address first.";return}try{await sendPasswordResetEmail(auth,email)}catch{}$("loginMessage").textContent="If the account exists, password reset instructions have been sent."};
$("signOutBtn").onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){$("dashboardView").hidden=true;$("loginView").hidden=false;return}try{const s=await getDoc(doc(db,"users",user.uid)),p=s.exists()?s.data():null;if(!p||p.active!==true||!["owner","administrator","editor"].includes(p.role)){await signOut(auth);$("loginMessage").textContent="This account is not authorized.";return}$("loginView").hidden=true;$("dashboardView").hidden=false;$("roleText").textContent=p.role;$("signedInName").textContent=p.displayName||user.email;await loadAll()}catch(e){await signOut(auth);$("loginMessage").textContent=err(e)}});
$$(".nav-item").forEach(b=>b.onclick=()=>{$$(".nav-item").forEach(x=>x.classList.toggle("active",x===b));$$(".panel").forEach(x=>x.classList.toggle("active",x.dataset.panelContent===b.dataset.panel));$("panelTitle").textContent=b.textContent});
async function loadAll(){await Promise.all([loadHome(),loadApple(),loadSettings(),loadSections(),loadAnnouncements(),loadEvents()])}
async function loadHome(){const x=await read("siteContent","homepage",defaults.home);$("homeHeroTitle").value=x.heroTitle;$("homeHeroSubtitle").value=x.heroSubtitle;$("homeHeroButton").value=x.heroButton;$("homeAboutTitle").value=x.aboutTitle;$("homeAboutText").value=x.aboutText}
$("homepageForm").onsubmit=async e=>{e.preventDefault();try{await setDoc(doc(db,"siteContent","homepage"),{heroTitle:$("homeHeroTitle").value.trim(),heroSubtitle:$("homeHeroSubtitle").value.trim(),heroButton:$("homeHeroButton").value.trim(),aboutTitle:$("homeAboutTitle").value.trim(),aboutText:$("homeAboutText").value.trim(),updatedAt:serverTimestamp()},{merge:true});await log("updated","siteContent/homepage");msg("Homepage saved.")}catch(x){msg(err(x),"error")}};
async function loadApple(){const x=await read("siteContent","appleDay",defaults.apple);$("appleAdminTitle").value=x.title;$("appleAdminDate").value=x.date;$("appleAdminLocation").value=x.location;$("appleAdminUrl").value=x.donationUrl;$("appleAdminRaised").value=x.amountRaised;$("appleAdminGoal").value=x.goal;$("appleAdminDescription").value=x.description;$("statRaised").textContent=new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0}).format(Number(x.amountRaised)||0)}
$("appleForm").onsubmit=async e=>{e.preventDefault();try{await setDoc(doc(db,"siteContent","appleDay"),{title:$("appleAdminTitle").value.trim(),date:$("appleAdminDate").value.trim(),location:$("appleAdminLocation").value.trim(),donationUrl:$("appleAdminUrl").value.trim(),amountRaised:Number($("appleAdminRaised").value)||0,goal:Math.max(1,Number($("appleAdminGoal").value)||1),description:$("appleAdminDescription").value.trim(),updatedAt:serverTimestamp()},{merge:true});await log("updated","siteContent/appleDay");await loadApple();msg("Apple Day details saved.")}catch(x){msg(err(x),"error")}};
async function loadSettings(){const x=await read("settings","general",defaults.settings);$("settingsGroupName").value=x.groupName;$("settingsEmail").value=x.publicEmail||"";$("settingsPhone").value=x.phone||"";$("settingsLocation").value=x.meetingLocation||"";$("settingsCity").value=x.city||"";$("settingsProvince").value=x.province||""}
$("settingsForm").onsubmit=async e=>{e.preventDefault();try{await setDoc(doc(db,"settings","general"),{groupName:$("settingsGroupName").value.trim(),publicEmail:$("settingsEmail").value.trim(),phone:$("settingsPhone").value.trim(),meetingLocation:$("settingsLocation").value.trim(),city:$("settingsCity").value.trim(),province:$("settingsProvince").value.trim(),updatedAt:serverTimestamp()},{merge:true});await log("updated","settings/general");msg("Settings saved.")}catch(x){msg(err(x),"error")}};
async function loadSections(){const snap=await getDocs(query(collection(db,"sections"),orderBy("order","asc"))),items=snap.docs.map(d=>({id:d.id,...d.data()}));$("statSections").textContent=items.filter(x=>x.active!==false).length;$("sectionsList").innerHTML=items.map(x=>`<div class="editor-row"><div><h3>${esc(x.displayName||x.name||x.id)}</h3><p>${esc(x.ageRange||"")} · ${x.active===false?"Hidden":"Visible"}</p></div><button class="button button-small button-secondary edit-section" data-id="${esc(x.id)}">Edit</button></div>`).join("")||"<p>No sections found.</p>";$$(".edit-section").forEach(b=>b.onclick=()=>openSection(items.find(x=>x.id===b.dataset.id)))}
function openSection(x){editor={type:"section",id:x.id};$("dialogTitle").textContent="Edit "+(x.displayName||x.id);$("dialogFields").innerHTML=`<label>Display name<input name="displayName" value="${esc(x.displayName||x.name||"")}" required></label><label>Age range<input name="ageRange" value="${esc(x.ageRange||"")}"></label><label>Description<textarea name="description" rows="4">${esc(x.description||"")}</textarea></label><label>Order<input name="order" type="number" step="1" value="${Number(x.order)||0}"></label><label>Slug<input name="slug" value="${esc(x.slug||x.id)}"></label><label><span><input name="active" type="checkbox" ${x.active!==false?"checked":""}> Visible on website</span></label>`;$("editorDialog").showModal()}
async function loadAnnouncements(){const snap=await getDocs(query(collection(db,"announcements"),orderBy("createdAt","desc"))),items=snap.docs.map(d=>({id:d.id,...d.data()}));$("statAnnouncements").textContent=items.filter(x=>x.published).length;$("announcementsList").innerHTML=items.map(x=>row(x,"announcement")).join("")||"<p>No announcements found.</p>";bindRows(items,"announcement")}
async function loadEvents(){const snap=await getDocs(query(collection(db,"events"),orderBy("start","asc"))),items=snap.docs.map(d=>({id:d.id,...d.data()}));$("statEvents").textContent=items.filter(x=>x.published).length;$("eventsList").innerHTML=items.map(x=>row(x,"event")).join("")||"<p>No events found.</p>";bindRows(items,"event")}
function row(x,type){return `<div class="editor-row"><div><h3>${esc(x.title||"Untitled")}</h3><p>${x.published?"Published":"Draft"} · ${esc(type==="event"?(x.location||"No location"):(x.content||"").slice(0,100))}</p></div><div class="row-actions"><button class="button button-small button-secondary edit-${type}" data-id="${esc(x.id)}">Edit</button><button class="danger delete-${type}" data-id="${esc(x.id)}">Delete</button></div></div>`}
function bindRows(items,type){$$(".edit-"+type).forEach(b=>b.onclick=()=>type==="event"?openEvent(items.find(x=>x.id===b.dataset.id)):openAnnouncement(items.find(x=>x.id===b.dataset.id)));$$(".delete-"+type).forEach(b=>b.onclick=()=>remove(type==="event"?"events":"announcements",b.dataset.id,type==="event"?loadEvents:loadAnnouncements))}
$("newAnnouncement").onclick=()=>openAnnouncement({published:true});$("newEvent").onclick=()=>openEvent({published:true});
function openAnnouncement(x){editor={type:"announcement",id:x.id||null};$("dialogTitle").textContent=x.id?"Edit announcement":"New announcement";$("dialogFields").innerHTML=`<label>Title<input name="title" value="${esc(x.title||"")}" required></label><label>Content<textarea name="content" rows="5" required>${esc(x.content||"")}</textarea></label><label><span><input name="published" type="checkbox" ${x.published!==false?"checked":""}> Published</span></label>`;$("editorDialog").showModal()}
const dto=v=>{const d=v?.toDate?v.toDate():v?new Date(v):null;if(!d||isNaN(d))return"";return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
function openEvent(x){editor={type:"event",id:x.id||null};$("dialogTitle").textContent=x.id?"Edit event":"New event";$("dialogFields").innerHTML=`<label>Title<input name="title" value="${esc(x.title||"")}" required></label><label>Location<input name="location" value="${esc(x.location||"")}"></label><label>Start<input name="start" type="datetime-local" value="${dto(x.start)}" required></label><label>End<input name="end" type="datetime-local" value="${dto(x.end)}"></label><label>Description<textarea name="description" rows="4">${esc(x.description||"")}</textarea></label><label><span><input name="published" type="checkbox" ${x.published!==false?"checked":""}> Published</span></label>`;$("editorDialog").showModal()}
$("editorForm").onsubmit=async e=>{e.preventDefault();if(e.submitter?.value==="cancel"||!editor)return;const f=new FormData(e.currentTarget);try{if(editor.type==="section"){await updateDoc(doc(db,"sections",editor.id),{displayName:String(f.get("displayName")).trim(),ageRange:String(f.get("ageRange")).trim(),description:String(f.get("description")).trim(),order:Number(f.get("order"))||0,slug:String(f.get("slug")).trim(),active:f.get("active")==="on",updatedAt:serverTimestamp()});await loadSections()}else if(editor.type==="announcement"){const p={title:String(f.get("title")).trim(),content:String(f.get("content")).trim(),published:f.get("published")==="on",updatedAt:serverTimestamp()};editor.id?await updateDoc(doc(db,"announcements",editor.id),p):await addDoc(collection(db,"announcements"),{...p,createdAt:serverTimestamp()});await loadAnnouncements()}else{const start=new Date(String(f.get("start"))),end=String(f.get("end"));const p={title:String(f.get("title")).trim(),location:String(f.get("location")).trim(),description:String(f.get("description")).trim(),start:Timestamp.fromDate(start),end:Timestamp.fromDate(end?new Date(end):start),published:f.get("published")==="on",updatedAt:serverTimestamp()};editor.id?await updateDoc(doc(db,"events",editor.id),p):await addDoc(collection(db,"events"),{...p,createdAt:serverTimestamp()});await loadEvents()}await log(editor.id?"updated":"created",editor.type);$("editorDialog").close();msg("Changes saved.")}catch(x){msg(err(x),"error")}};
async function remove(c,id,reload){if(!confirm("Delete this item permanently?"))return;try{await deleteDoc(doc(db,c,id));await log("deleted",c+"/"+id);await reload();msg("Item deleted.")}catch(x){msg(err(x),"error")}}
$("passwordForm").onsubmit=async e=>{e.preventDefault();const cur=$("currentPassword").value,n=$("newPassword").value,c=$("confirmPassword").value;if(n!==c){msg("The new passwords do not match.","error");return}try{const u=auth.currentUser;await reauthenticateWithCredential(u,EmailAuthProvider.credential(u.email,cur));await updatePassword(u,n);e.currentTarget.reset();msg("Password changed successfully.")}catch(x){msg(err(x),"error")}};
